import assert from 'node:assert/strict';
import {createAnalysisJob,finishAnalysisJob} from '../analysis-pipeline.js';
const docs=[{name:'원고.pdf',pages:[{text:'원고는 임대차기간이 5년이라고 주장하였다.'},{text:''}]},{name:'피고.pdf',pages:[{text:'피고는 임대차기간이 2년이라고 주장하였다.'}]}];
const job=createAnalysisJob(docs,{batches:{maxBatchPages:1,maxBatchChars:100}});
assert.equal(job.plan.batches.length,2);
const responses=job.plan.batches.map(b=>({batch:b.batch,payload:{schema:'squidlaw-findings-v1',findings:[{title:'원문 주장 후보',citations:[{document:b.pages[0].document,page:b.pages[0].page,quote:b.pages[0].text}]}]}}));
const complete=finishAnalysisJob(job,responses);
assert.equal(complete.sourceReady,true);
assert.equal(complete.findings.length,2);
assert.equal(complete.diagnostics.unreadablePages,1);
const partial=finishAnalysisJob(job,responses.slice(0,1));
assert.equal(partial.sourceReady,false);
assert.deepEqual(partial.diagnostics.missingBatches,[2]);
const tampered=structuredClone(responses);
tampered[1].payload.findings[0].citations[0].quote='이 페이지에 없는 완전히 다른 허위 문구입니다.';
const invalid=finishAnalysisJob(job,tampered);
assert.equal(invalid.sourceReady,false);
assert.equal(invalid.diagnostics.needsReview,1);
assert.throws(()=>finishAnalysisJob(job,[responses[0],responses[0]]),/DUPLICATE_BATCH_RESPONSE/);
assert.throws(()=>finishAnalysisJob(job,[{batch:9,payload:responses[0].payload}]),/UNKNOWN_BATCH_RESPONSE/);
console.log('PASS: end-to-end source preparation, batching, citation validation, and complete merge');
