import assert from 'node:assert/strict';
import {runPrivateCaseReport} from '../analysis-private-case-runner.js';
const documents=[{name:'원고.pdf',pages:[{text:'원고는 계약기간 5년을 주장한다.'}]},{name:'피고.pdf',pages:[{text:'피고는 계약기간 2년을 주장한다.'}]}];
const a={document:'원고.pdf',page:1,quote:'계약기간 5년을 주장한다'};
const b={document:'피고.pdf',page:1,quote:'계약기간 2년을 주장한다'};
const analysis={schema:'squidlaw-merged-analysis-v1',sourceReady:true,diagnostics:{},findings:[{title:'기간 주장',citations:[a],citationChecks:[{verification:{status:'matched'}}]}]};
const comparison={schema:'squidlaw-private-comparisons-v1',sourceReady:true,diagnostics:{},comparisons:[{reference:'소갑 제3호증',relation:'different_positions',explanation:'기간 주장 상이',sourceReady:true,citations:[{...a,verification:{status:'matched'}},{...b,verification:{status:'matched'}}]}]};
const credentials={apiKey:'mock-key',model:'gpt-test'};
let calls=[];
const analyze=async(_docs,opts)=>{calls.push('analyze');assert.equal(opts.enabled,true);assert.equal(opts.apiKey,'mock-key');return analysis;};
const compare=async(_docs,opts)=>{calls.push('compare');assert.equal(opts.enabled,true);return comparison;};
await assert.rejects(runPrivateCaseReport(documents,{...credentials,analyze,compare}),/PRIVATE_CASE_REPORT_DISABLED/);
assert.deepEqual(calls,[]);
const result=await runPrivateCaseReport(documents,{...credentials,enabled:true,analyze,compare});
assert.equal(result.sourceReady,true);
assert.equal(result.diagnostics.comparisonPerformed,true);
assert.equal(result.diagnostics.unreadablePages,0);
assert.equal(result.diagnostics.verifiedCitationCount,3);
assert.equal(result.diagnostics.unverifiedCitationCount,0);
assert.match(result.text,/최종 원문 재검증 일치 인용: 3건/);
assert.match(result.text,/최종 원문 재검증 확인 필요 인용: 0건/);
assert.deepEqual(result.diagnostics.uncitedDocuments,[]);
assert.deepEqual(result.diagnostics.missingBatches,[]);
assert.deepEqual(calls,['analyze','compare']);
assert.match(result.text,/원고.pdf · 1쪽 · 원문 일치/);
assert.match(result.text,/피고.pdf · 1쪽 · 원문 일치/);
calls=[];
const badAnalysis={...analysis,findings:[{...analysis.findings[0],citations:[{...a,quote:'원문에 없는 문장'}]}]};
const resultBad=await runPrivateCaseReport(documents,{...credentials,enabled:true,analyze:async()=>badAnalysis,compare});
assert.equal(resultBad.sourceReady,false);
assert.equal(resultBad.diagnostics.verifiedCitationCount,2);
assert.equal(resultBad.diagnostics.unverifiedCitationCount,1);
const isolated=await runPrivateCaseReport(documents,{...credentials,enabled:true,analyze:async()=>badAnalysis,compare:async()=>({...comparison,comparisons:[]})});
assert.deepEqual(isolated.diagnostics.uncitedDocuments,['원고.pdf','피고.pdf']);
assert.equal(isolated.report.diagnostics.citedReadablePages,0);
assert.equal(isolated.report.diagnostics.uncitedReadablePages,2);
assert.match(isolated.text,/원문 일치가 확인된 인용 문서: 0개/);
assert.match(isolated.text,/원문 일치가 확인된 서로 다른 페이지: 0쪽/);
assert.match(resultBad.text,/출처 확인 필요/);
calls=[];
await assert.rejects(runPrivateCaseReport(documents,{...credentials,enabled:true,analyze:async()=>({...analysis,sourceReady:false}),compare}),/ANALYSIS_SOURCE_NOT_READY/);
assert.deepEqual(calls,[],'comparison should not run after failed analysis');
const empty=await runPrivateCaseReport(documents,{...credentials,enabled:true,analyze,compare:async()=>({...comparison,comparisons:[],sourceReady:false})});
assert.equal(empty.sourceReady,false);
console.log('PASS: private case runner requires opt-in, runs sequentially and rechecks original citations');
