import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../analysis-merge.js',import.meta.url),'utf8');
const {mergeCheckedBatches}=await import('data:text/javascript;charset=utf-8,'+encodeURIComponent(source));
const expected={schema:'squidlaw-analysis-batches-v1',batches:[{batch:1},{batch:2}]};
const citation={verification:{status:'matched'}};
const result=(batch,sourceReady=true,checks=[citation])=>({schema:'squidlaw-checked-batch-v1',batch,sourceReady,quality:{matched:1},findings:[{title:'분석 후보 '+batch,citationChecks:checks}]});
const complete=mergeCheckedBatches(expected,[result(2),result(1)]);
assert.equal(complete.sourceReady,true);
assert.deepEqual(complete.findings.map(f=>f.sourceBatch),[1,2]);
const partial=mergeCheckedBatches(expected,[result(1)]);
assert.equal(partial.sourceReady,false);
assert.deepEqual(partial.diagnostics.missingBatches,[2]);
const invalid=mergeCheckedBatches(expected,[result(1),result(2,true,[{verification:{status:'unmatched'}}])]);
assert.equal(invalid.sourceReady,false);
assert.equal(invalid.diagnostics.needsReview,1);
assert.equal(mergeCheckedBatches(expected,[result(1),result(2,false)]).sourceReady,false);
assert.throws(()=>mergeCheckedBatches(expected,[result(1),result(1)]),/DUPLICATE_BATCH_RESULT/);
assert.throws(()=>mergeCheckedBatches(expected,[result(3)]),/UNEXPECTED_BATCH_RESULT/);
console.log('PASS: checked batch merge preserves order and blocks missing, unsupported or duplicate batches');
