import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const src=readFileSync(new URL('../analysis-quality.js',import.meta.url),'utf8');
const {summarizeCitationChecks,isSourceReadyForReview}=await import('data:text/javascript;charset=utf-8,'+encodeURIComponent(src));
const matched={verification:{status:'matched'}};
const missing={verification:{status:'missing_document'}};
const good=[{citationChecks:[matched,matched]},{citationChecks:[matched]}];
assert.deepEqual({...summarizeCitationChecks(good).byStatus},{matched:3});
assert.equal(summarizeCitationChecks(good).verifiedFindings,2);
assert.equal(isSourceReadyForReview(good),true);
const mixed=[...good,{citationChecks:[matched,missing]},{citationChecks:[]}];
const result=summarizeCitationChecks(mixed);
assert.equal(result.findings,4);
assert.equal(result.verifiedFindings,2);
assert.equal(result.needsReviewFindings,2);
assert.equal(result.matched,4);
assert.equal(result.unmatched,1);
assert.equal(result.missingCitations,1);
assert.equal(result.byStatus.missing_document,1);
assert.equal(isSourceReadyForReview(mixed),false);
assert.equal(isSourceReadyForReview([]),false);
console.log('PASS: citation coverage counts, missing citations, and source readiness gate');
