import assert from 'node:assert/strict';
import {prepareAnalysisInput} from '../analysis-input.js';
import {assembleVerifiedCaseAnalysis} from '../analysis-case-report.js';
import {formatCaseReportText} from '../analysis-case-report-text.js';
const docs=[{name:'계약서.pdf',pages:[{text:'계약기간은 5년이다.'},{text:''},{text:'기간 변경 합의는 없었다.'}]}];
const input=prepareAnalysisInput(docs);
assert.deepEqual(input.diagnostics.unreadableDetails,[{document:'계약서.pdf',page:2,totalPages:3}]);
const quote={document:'계약서.pdf',page:1,quote:'계약기간은 5년이다.'};
const analysis={schema:'squidlaw-merged-analysis-v1',sourceReady:true,diagnostics:{unreadableDetails:input.diagnostics.unreadableDetails},findings:[{title:'기간',citations:[quote]}]};
const comparison={schema:'squidlaw-private-comparisons-v1',sourceReady:false,diagnostics:{},comparisons:[]};
const report=assembleVerifiedCaseAnalysis(docs,analysis,comparison);
const txt=formatCaseReportText(report);
assert.match(txt,/「계약서.pdf」 총 3페이지 중 2페이지는 텍스트를 추출하지 못하여/);
assert.match(txt,/이미지나 스캔 원본의 글씨도 흐릿하여 실제로 판독하기 어렵다면/);
assert.match(txt,/선명하게 다시 스캔한 후 업로드/);
assert.match(txt,/재판부가 판독하기 어려워 원본 제출/);
assert.match(txt,/텍스트 추출 실패만으로 원본 자체가 판독 불가능하다고 단정할 수는 없습니다/);
assert.match(txt,/계약서.pdf · 1쪽 · 원문 일치/);
assert.throws(()=>prepareAnalysisInput([{name:'전체스캔.pdf',pages:[{text:''}]}]),/NO_READABLE_TEXT/);
console.log('PASS: partially unreadable PDFs produce exact, friendly omission notice while readable pages are analyzed');
