document.addEventListener('DOMContentLoaded',()=>{const sidebar=document.createElement('aside');sidebar.id='skynetSidebar';sidebar.innerHTML='<button type="button" id="skynetSidebarToggle" aria-label="관리 도구 펼치기" aria-expanded="false">☰</button><nav id="skynetSidebarPanel" aria-label="SKYNET 관리 도구"><strong>관리 도구</strong></nav>';document.body.append(sidebar);const tools=document.createElement('div');tools.id='skynetToolContent';tools.innerHTML='<button class="skynetToolClose" type="button">✕ 닫기</button>';document.body.append(tools);const panel=document.getElementById('skynetSidebarPanel'),toggle=document.getElementById('skynetSidebarToggle');const items=[['indexManager','장기기억 검색 인덱스'],['timelineManager','사건별 타임라인'],['dataManager','저장 데이터 관리']];const profile=[...document.querySelectorAll('body > section')].find(n=>n.querySelector('h3')?.textContent.includes('오징어 장기 성격'));if(profile){profile.id='skynetProfileManager';items.push(['skynetProfileManager','오징어 성격 · 사용자 취향'])}const memory=document.querySelector('section.internal-memory');if(memory){memory.id='skynetMemoryManager';items.push(['skynetMemoryManager','기억 작업방'])}const nodes=[];for(const [id,label] of items){const node=document.getElementById(id);if(!node)continue;nodes.push(node);tools.append(node);node.hidden=true;const b=document.createElement('button');b.type='button';b.className='skynetToolLink';b.textContent=label;b.onclick=()=>{nodes.forEach(n=>n.hidden=n!==node);panel.querySelectorAll('.skynetToolLink').forEach(x=>x.classList.toggle('active',x===b));tools.classList.add('active')};panel.append(b)}toggle.onclick=()=>{const open=sidebar.classList.toggle('open');document.body.classList.toggle('skynet-sidebar-open',open);toggle.setAttribute('aria-expanded',String(open));if(!open)tools.classList.remove('active')};tools.querySelector('.skynetToolClose').onclick=()=>{tools.classList.remove('active');nodes.forEach(n=>n.hidden=true)}});
document.addEventListener('DOMContentLoaded',()=>{
const composer=document.getElementById('chatComposer'),bar=composer?.querySelector('.composerbar'),reason=document.getElementById('skynetReasoning'),input=document.getElementById('chatInput');
if(!composer||!bar)return;
if(input)input.placeholder='SKYNET에게 이야기하세요.';
const helper=bar.querySelector('.muted');if(helper)helper.textContent='파일은 대화창에 끌어놓을 수 있습니다.';
const label=reason?.parentElement;if(label){label.id='skynetReasoningLabel';label.textContent='추론 수준 ';label.append(reason);bar.insertBefore(label,document.getElementById('sendChat'))}
const attachment=document.getElementById('archivePickButton');if(attachment){attachment.title='파일 첨부';attachment.setAttribute('aria-label','파일 첨부')}
const send=document.getElementById('sendChat');if(send){send.title='보내기';send.setAttribute('aria-label','보내기')}
const status=document.getElementById('archiveStatus');if(status){status.textContent='파일은 대화창에 끌어놓을 수 있습니다.';const observer=new MutationObserver(()=>{if(status.textContent==='파일을 선택해 첨부한 뒤 보내기를 누르세요.')status.textContent='파일은 대화창에 끌어놓을 수 있습니다.';status.classList.toggle('skynet-status-alert',/실패|오류|제한|초과|필요/.test(status.textContent))});observer.observe(status,{childList:true,characterData:true,subtree:true})}
const pending=document.getElementById('pendingFiles');if(pending){const urls=new Map(),imageFiles=new Map();const capture=files=>{for(const f of files)if(f.type.startsWith('image/'))imageFiles.set(f.name,f)};composer.addEventListener('drop',e=>capture(e.dataTransfer?.files||[]),true);document.getElementById('archivePickInput')?.addEventListener('change',e=>capture(e.target.files||[]),true);const update=()=>{const nodes=[...pending.querySelectorAll('[data-archive-pending]')];for(const n of nodes){if(n.dataset.previewReady)continue;n.dataset.previewReady='1';const match=n.textContent.match(/📎\s*(.*?)\s*·/);const filename=match?.[1];const picker=document.getElementById('archivePickInput');const file=imageFiles.get(filename)||[...(picker?.files||[])].find(f=>f.name===filename);if(file?.type.startsWith('image/')){const img=document.createElement('img');img.alt=filename;const url=URL.createObjectURL(file);urls.set(n,url);img.src=url;n.prepend(img)}else{const mark=document.createElement('span');mark.textContent='📄';mark.style.fontSize='26px';n.prepend(mark)}}for(const [n,url] of urls){if(!n.isConnected){URL.revokeObjectURL(url);urls.delete(n)}}};new MutationObserver(update).observe(pending,{childList:true,subtree:true});update()}
});
