export default async function handler(req,res){
 const send=(code,obj)=>res.status(code).setHeader('Cache-Control','no-store').json(obj);
 if(req.method!=='POST'){res.setHeader('Allow','POST');return send(405,{error:'POST only'})}
 const auth=typeof req.headers.authorization==='string'?req.headers.authorization:'';
 let valid=false;try{const raw=Buffer.from(auth.replace(/^Basic /,''),'base64').toString();valid=auth.startsWith('Basic ')&&raw==='admin:'+process.env.ADMIN_PASSWORD&&!!process.env.ADMIN_PASSWORD}catch{}
 if(!valid)return send(401,{error:'관리자 인증 필요'});
 const key=process.env.OPENAI_API_KEY;if(!key)return send(503,{error:'OPENAI_API_KEY 환경변수 설정 필요'});
 const input=req.body&&typeof req.body==='object'&&!Array.isArray(req.body)?req.body:{};const messages=Array.isArray(input.messages)?input.messages:[];const memories=Array.isArray(input.memories)?input.memories:[];
 if(messages.length>35||memories.length>30)return send(400,{error:'요청 크기 제한'});if(messages.some(x=>x&&typeof x.content==='string'&&x.content.length>12000)||memories.some(x=>typeof x==='string'&&x.length>1800))return send(413,{error:'메시지 또는 기억 항목이 너무 깁니다'});if(!messages.some(x=>x&&x.role==='user'&&typeof x.content==='string'&&x.content.trim()))return send(400,{error:'질문 내용이 없습니다'});
 const clean=messages.filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string'&&x.content.trim()).slice(-24).map(x=>({role:x.role,content:x.content.slice(0,12000)}));
 const context=memories.filter(x=>typeof x==='string'&&x.trim()).slice(0,20).map(x=>x.slice(0,1800)).join('\n---\n');
 try{const upstream=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:JSON.stringify({model:process.env.SKYNET_MODEL||'gpt-4.1-mini',messages:[{role:'system',content:'너는 SKYNET, 한국어로 대화하는 개인 AI 동반자다. SKYNET은 오징어로펌(squidlaw.co.kr)의 관리자 전용 AI 친구 실험 서비스이며, 법률 사건 분석 기능과는 별개다. 개발 현황: 관리자 페이지 /admin/skynet.html에 대화창이 있고 OpenAI API와 연결되어 있다. 기억 추가, 브라우저 localStorage 저장, TXT/JSON 간단 가져오기, 정규화된 완전 동일 문장 중복 통합, 규칙 기반 카테고리 분류, 검색, JSON 백업이 구현되어 있다. ChatGPT 내보내기 파일의 텍스트 가져오기는 구현되어 있다. 서버 영구 저장, 기기간 동기화, 전체 메타데이터 이전, 의미 기반 중복 정제, 자율 카테고리 생성은 아직 구현되지 않았다. 사용자의 목표는 잡담까지 포함해 서로 다른 의미를 평생 보존하고 중복만 합치며 주제를 AI가 스스로 정리하는 저비용 AI 친구다. 대화 중 개발 진행을 물으면 이 사실을 정확히 말하고 사용자에게 다시 설명해 달라고 요구하지 않는다. 사용자의 과거 기억은 아래에 제공된다. 기억을 근거로 삼되 추측을 사실처럼 말하지 말고, 과거 기록과 현재 지시가 다르면 확인한다.\n기억:\n'+context},...clean],max_completion_tokens:1600})});let data;try{data=await upstream.json()}catch{return send(502,{error:'AI 서비스 응답 형식 오류'})}if(!upstream.ok)return send(502,{error:'AI 서비스 응답 오류',detail:typeof data?.error?.message==='string'?data.error.message.slice(0,300):'unknown'});if(typeof data?.choices?.[0]?.message?.content!=='string'||!data.choices[0].message.content.trim())return send(502,{error:'AI 응답이 비어 있습니다'});return send(200,{reply:data.choices[0].message.content})}catch(e){return send(502,{error:'AI 연결 실패'})}
}