import {put,list,get} from '@vercel/blob';
import {createHash} from 'node:crypto';
const base='skynet/records/';
export const normalize=s=>String(s||'').normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();
export const recordId=s=>createHash('sha256').update(normalize(s)).digest('hex');
export async function readJSON(path,limit=4500000){const item=await get(path,{access:'private'});if(!item||item.statusCode!==200)return null;const parts=[];let size=0;for await(const chunk of item.stream){const b=Buffer.from(chunk);size+=b.length;if(size>limit)throw Error('record too large');parts.push(b)}return JSON.parse(Buffer.concat(parts).toString('utf8'))}
export async function allBlobs(prefix,cap=100000){const files=[];let cursor;do{const page=await list({prefix,limit:1000,...(cursor?{cursor}:{})});files.push(...page.blobs);cursor=page.hasMore?page.cursor:undefined}while(cursor&&files.length<cap);return files}
export async function appendRecords(records){let added=0,duplicates=0;for(const r of records){const text=String(r?.text||'').trim();if(!text)continue;const id=recordId(text),path=base+id+'.json';try{await put(path,JSON.stringify({id,text,category:String(r.category||'').slice(0,100),at:String(r.at||new Date().toISOString()),repeat:Math.max(1,Number(r.repeat)||1)}),{access:'private',addRandomSuffix:false,allowOverwrite:false,contentType:'application/json'});added++}catch(e){if(/already exists|already been|conflict|409|BlobAlreadyExists/i.test(String(e?.message||e)||String(e?.code||'')))duplicates++;else throw e}}return {added,duplicates}}
export async function loadRecords(){const files=await allBlobs(base);const records=[];for(let i=0;i<files.length;i+=16){const chunk=await Promise.all(files.slice(i,i+16).map(async f=>{try{return await readJSON(f.pathname,50000)}catch{return null}}));records.push(...chunk.filter(Boolean))}return records}
